blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/sandersgutierrez/sandersgutierrez.github.io/discussions
    about: Ask me any question about this website development
  - name: Feature request
    url: https://github.com/sandersgutierrez/sandersgutierrez.github.io/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
